title = "Ishan Gupta"
baseURL = "https://guptaishan.live"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
disqusShortname = "ishangupta"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Ishan Gupta"
  author = "IshanGupta"
  description = "Full-stack web developer based in Banglore, India."
  logoBig = "/images/ishan.png"
  logoSmall = "/images/ishan.png"
  favicon = "/images/favicon.png"
  opengraphImage = "/images/ishan.png"
  email = "gupta.ishan@hotmail.com"
  googleTagManger = ""
  customCSS = false
  

  # Social media links in footer
  twitter = "ishan_gupt"
  linkedin = "ig01"
  github = "ishan-gupt"
  facebook = "ishangupt"
 

  # Copyright and theme author credit in footer
  copyright = true
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "/scripts/highlight.pack.js"# For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
#  ajaxFormspree = false
 # ajaxFormspreeGold = false
  #ajaxBasin = "https://usebasin.com/f/0eae7044d4c2"

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Projects"
  url  = "/#work"
  weight = 2
[[menu.main]]
  name = "Certifications"
  url  = "/#certificates"
  weight = 3

